/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.t0ast.parkour.visualization;

import java.awt.Color;
import java.util.function.Consumer;
import javax.swing.colorchooser.DefaultColorSelectionModel;

/**
 *
 * @author T0astBread
 */
public class ColorChooserDialog extends javax.swing.JPanel
{
    private ColorConfiguration colors;
    private Consumer<Color> colorChangeCallback;
    
    /**
     * Creates new form ColorChooserDialog
     */
    public ColorChooserDialog()
    {
        initComponents();
        
        this.colorChooser.getSelectionModel().addChangeListener(e ->
        {
            if(this.colorChangeCallback != null) this.colorChangeCallback.accept(((DefaultColorSelectionModel) e.getSource()).getSelectedColor());
        });
    }

    public ColorChooserDialog(ColorConfiguration colors)
    {
        this();
        this.colors = colors;
        rdoBackgroundActionPerformed(null);
    }
    
    private void changeCurrentValue(Color colorToSet, Consumer<Color> updateCallback)
    {
        this.colorChangeCallback = updateCallback;
        this.colorChooser.setColor(colorToSet);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        grpValues = new javax.swing.ButtonGroup();
        colorChooser = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        rdoBackground = new javax.swing.JRadioButton();
        rdoFloor = new javax.swing.JRadioButton();
        rdoBody = new javax.swing.JRadioButton();
        rdoHead = new javax.swing.JRadioButton();
        rdoBorders = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Values"));

        grpValues.add(rdoBackground);
        rdoBackground.setSelected(true);
        rdoBackground.setText("Background");
        rdoBackground.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdoBackgroundActionPerformed(evt);
            }
        });

        grpValues.add(rdoFloor);
        rdoFloor.setText("Floor");
        rdoFloor.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdoFloorActionPerformed(evt);
            }
        });

        grpValues.add(rdoBody);
        rdoBody.setText("Entity Body");
        rdoBody.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdoBodyActionPerformed(evt);
            }
        });

        grpValues.add(rdoHead);
        rdoHead.setText("Entity Head");
        rdoHead.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdoHeadActionPerformed(evt);
            }
        });

        grpValues.add(rdoBorders);
        rdoBorders.setText("Entity Borders");
        rdoBorders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdoBordersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdoFloor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdoBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdoHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(rdoBorders, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rdoBackground)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoFloor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBody)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBorders)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoBackgroundActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdoBackgroundActionPerformed
    {//GEN-HEADEREND:event_rdoBackgroundActionPerformed
        changeCurrentValue(this.colors.getBackground(), this.colors::setBackground);
    }//GEN-LAST:event_rdoBackgroundActionPerformed

    private void rdoFloorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdoFloorActionPerformed
    {//GEN-HEADEREND:event_rdoFloorActionPerformed
        changeCurrentValue(this.colors.getFloor(), this.colors::setFloor);
    }//GEN-LAST:event_rdoFloorActionPerformed

    private void rdoBodyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdoBodyActionPerformed
    {//GEN-HEADEREND:event_rdoBodyActionPerformed
        changeCurrentValue(this.colors.getEntityBody(), this.colors::setEntityBody);
    }//GEN-LAST:event_rdoBodyActionPerformed

    private void rdoHeadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdoHeadActionPerformed
    {//GEN-HEADEREND:event_rdoHeadActionPerformed
        changeCurrentValue(this.colors.getEntityHead(), this.colors::setEntityHead);
    }//GEN-LAST:event_rdoHeadActionPerformed

    private void rdoBordersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdoBordersActionPerformed
    {//GEN-HEADEREND:event_rdoBordersActionPerformed
        changeCurrentValue(this.colors.getEntityBorders(), this.colors::setEntityBorders);
    }//GEN-LAST:event_rdoBordersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.ButtonGroup grpValues;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdoBackground;
    private javax.swing.JRadioButton rdoBody;
    private javax.swing.JRadioButton rdoBorders;
    private javax.swing.JRadioButton rdoFloor;
    private javax.swing.JRadioButton rdoHead;
    // End of variables declaration//GEN-END:variables
}
